const layout = {
  menuTree: [
    {icon:'el-icon-s-platform', label:'百度一下',prop:'百度一下',page:'https://www.baidu.com/'},
    {
      icon: 'el-icon-s-platform',
      label: '我的页面',
      children: [
        { label:'菜鸟教程',prop:'菜鸟教程',page:'https://www.runoob.com/'},
        { label:'W3CSchool',prop:'W3CSchool',page:'http://www.w3school.com.cn/'},
        { label:'一行代码搞定bug监控',prop:'一行代码搞定bug监控',page:'https://www.fundebug.com/?tdsourcetag=s_pcqq_aiomsg'},
        { label:'web开发人员必备工具包',prop:'web开发人员必备工具包（实现快速敲代码）',page:'https://docs.emmet.io/'},

      ],
    },
    {
      icon: 'el-icon-s-platform',
      label: 'UI相关',
      children: [
        { label:'UI颜色布料',prop:'UI颜色布料',page:'https://www.materialui.co/colors'},
        { label:'logo在线制作，有很多',prop:'logo在线制作，有很多',page:'http://www.logofree.cn/'},
        { label:'免费设计图，有很多',prop:'免费设计图，有很多',page:'https://www.chuangkit.com/designtools/designindex'},
        { label:'图片识别转换各种格式',prop:'图片试别转换各种格式，有很多，只列举了一个',page:'https://zhcn.109876543210.com/'},
      ],
    },
    {
      icon: 'el-icon-s-platform',
      label: '开发工具',
      children: [
        { label:'在线开发工具',prop:'在线开发工具',page:'https://tool.lu/c/developer'},
        { label:'在线编辑器',prop:'在线编辑器',page:'https://codesandbox.io/'},
        { label:'在线做图ProcessOn',prop:'在线做图ProcessOn',page:'https://www.processon.com/'},
        { label:'项目部署流程',prop:'项目部署流程',page:'https://cloud.tencent.com/developer/information/%E9%83%A8%E7%BD%B2%E6%9C%8D%E5%8A%A1%E5%99%A8%E6%AD%A5%E9%AA%A4'},
        { label:'正则表达式验证',prop:'验证正则表达式的可视化工具',page:'https://regexper.com/'},
        { label:'开源免费企业级CMS系统',prop:'开源、免费、企业级CMS系统',page:'https://www.siteserver.cn/'},
      ],
    },
    {
      icon: 'el-icon-s-platform',
      label: '前端',
      children: [
        { label:'MintUI',prop:'MintUI',page:'https://mint-ui.github.io/#!/zh-cn'},
        { label:'ElementUI',prop:'ElementUI',page:'https://element.eleme.cn/#/zh-CN'},
        { label:'iViewUI',prop:'iViewUI',page:'https://www.iviewui.com/'},
        { label:'cubeUI',prop:'cubeUI',page:'https://didi.github.io/cube-ui/#/zh-CN'},
        { label:'Antd',prop:'Antd',page:'https://ant.design/index-cn'},
        { label:'MUI',prop:'MUI',page:'http://dev.dcloud.net.cn/mui/'},
        { label:'Animate.CSS',prop:'Animate.CSS',page:'https://daneden.github.io/animate.css/'},
      ],
     },
     {
       icon: 'el-icon-s-platform',
       label: '直播|富文本',
       children: [
        { label:'富文本wangEditor',prop:'富文本编辑器wangEditor',page:'http://www.wangeditor.com/'},
        { label:'热力图插件',prop:'热力图插件',page:'https://www.patrick-wied.at/static/heatmapjs/'},
        { label:'视频监控直播的插件VLC',prop:'视频监控直播的插件VLC',page:'https://www.videolan.org/'},
        { label:'直播软件开发',prop:'直播软件开发',page:'http://www.nodemedia.cn/'},
        { label:'网易云信',prop:'网易云信',page:'https://netease.im/'},
      ],
    },
    {
        icon: 'el-icon-s-platform',
        label: '其他',
        children: [
        { label:'有道翻译API',prop:'有道翻译API',page:'http://fanyi.youdao.com/openapi?path=data-mode'},
        { label:'游戏开发',prop:'游戏开发',page:'http://phaser.io/'},
        { label:'处理时间与日期的JS库',prop:'处理时间与日期的JS库',page:'http://momentjs.cn/'},
        { label:'云小蜜智能机器人API',prop:'云小蜜智能机器人API',page:'https://help.aliyun.com/product/59495.html?spm=a2c4g.11186623.3.1.7dad1b005dRM5F'},
        { label:'短信验证码接口',prop:'短信验证码接口',page:'https://www.mysubmail.com/sms/api?tag=jq22'},
        { label:'榛子短信验证码接口',prop:'榛子短信验证码接口',page:'http://smsow.zhenzikj.com/'},
        { label:'草料二维码生成器',prop:'草料二维码生成器',page:'https://cli.im/'},
        { label:'RAP2假数据接口',prop:'RAP2假数据接口',page:'http://rap2.taobao.org/'},
        { label:'可扒的真实电商数据',prop:'可扒的真实电商数据',page:'http://www.xiongmaoyouxuan.com/#/'},
        { label:'免费接口',prop:'免费接口',page:'http://www.bejson.com/knownjson/webInterface/'},
        { label:'假数据接口（测试用）',prop:'假数据接口（测试用）',page:'http://jsonplaceholder.typicode.com/'},
        { label:'jQuery插件库',prop:'jQuery插件库',page:'http://www.jq22.com/search'},
        { label:'轮播图插件',prop:'轮播图插件',page:'https://www.swiper.com.cn/'},
        { label:'放大镜插件',prop:'放大镜插件',page:'http://www.elevateweb.co.uk/image-zoom/examples'},
        { label:'响应式瀑布流插件',prop:'响应式瀑布流插件',page:'http://www.jq22.com/jquery-info20261'},
        { label:'art-template模板引擎',prop:'art-template模板引擎',page:'https://aui.github.io/art-template/zh-cn/docs/'},
        { label:'ejs模板引擎',prop:'ejs模板引擎',page:'https://ejs.bootcss.com/'},
        { label:'小表情的emoji',prop:'小表情的emoji',page:'https://emojipedia.org/'},
        { label:'码云代码托管平台',prop:'码云代码托管平台',page:'https://gitee.com/'},
        { label:'码神岛',prop:'码神岛',page:'https://msd.misuland.com/'},
        { label:'掘金网',prop:'掘金网',page:'https://juejin.im/'},
        { label:'stack Overflow',prop:'stack Overflow',page:'https://stackoverflow.com/'},
        { label:'v2ex社区',prop:'v2ex社区',page:'https://www.v2ex.com/'},
        { label:'CtoLib码库',prop:'CtoLib码库',page:'https://www.ctolib.com'},
        { label:'牛客网',prop:'牛客网',page:'https://www.nowcoder.com'},
        { label:'FCC中文网',prop:'FCC中文网',page:'https://www.freecodecamp.one/'},
        { label:'Web 开发练习题',prop:'Web 开发练习题',page:'https://www.freecodecamp.org/'},
        { label:'阿里云',prop:'阿里云',page:'https://www.aliyun.com'},
        { label:'腾讯云',prop:'腾讯云',page:'https://cloud.tencent.com/'},
        { label:'html中文网',prop:'html中文网',page:'https://www.html.cn/'},
        { label:'hCoder',prop:'hCoder',page:'http://www.hcoder.net/'},
        { label:'React官网',prop:'React官网',page:'https://reactjs.org/'},
        { label:'Redux官网',prop:'Redux官网',page:'https://react-redux.js.org/'},
        { label:'React Router',prop:'React Router',page:'https://reacttraining.com/react-router/'},
        { label:'Vue官网',prop:'Vue官网',page:'https://cn.vuejs.org/'},
        { label:'NodeJS官网',prop:'NodeJS官网',page:'http://nodejs.cn/'},
        { label:'React Native',prop:'React Native',page:'https://reactnative.cn/'},
        { label:'uni-app',prop:'uni-app',page:'https://uniapp.dcloud.io/'},
        { label:'Mui',prop:'Mui',page:'https://dev.dcloud.net.cn/mui/'},
        { label:'Taro',prop:'Taro',page:'https://taro.aotu.io/?tdsourcetag=s_pcqq_aiomsg'},
        { label:'微信小程序开发者平台',prop:'微信小程序开发者平台',page:'https://developers.weixin.qq.com/'},
        { label:'微信开发者平台',prop:'微信开发者平台',page:'https://open.weixin.qq.com/'},
        { label:'钉钉开发者平台',prop:'钉钉开发者平台',page:'https://ding-doc.dingtalk.com/'},
        { label:'百度地图开发者平台',prop:'百度地图开发者平台',page:'https://passport.baidu.com'},
        { label:'DvaJS',prop:'DvaJS',page:'https://dvajs.com/'},
        { label:'jQuery官网',prop:'jQuery官网',page:'https://jquery.com/'},
        { label:'jQuery API',prop:'jQuery API中文文档【在线手册】',page:'http://jquery.cuishifeng.cn/'},
        { label:'ZeptoJS官网',prop:'ZeptoJS官网',page:'https://zeptojs.com/'},
        { label:'cheerioJS安装地址',prop:'cheerioJS安装地址',page:'https://www.npmjs.com/package/cheerio'},
        { label:'RequireJS官网',prop:'RequireJS官网',page:'https://requirejs.org/'},
        { label:'Sass官网',prop:'Sass官网（CSS预处理器，通过编程的方式来开发CSS）',page:'https://sass-lang.com/'},
        { label:'Less官网',prop:'Less官网（同上）',page:'http://lesscss.org/'},
        { label:'CSS参考笔记',prop:'CSS参考笔记',page:'http://css.doyoe.com/'},
        { label:'Bootstrap官网',prop:'Bootstrap官网',page:'https://www.bootcss.com/'},
        { label:'CSS优质内容网站',prop:'CSS优质内容网站',page:'https://css-tricks.com/'},
        { label:'CSS 优质内容网站',prop:'CSS 优质内容网站',page:'https://css-weekly.com/'},
        { label:'HTML 优质内容网站',prop:'HTML 优质内容网站',page:'https://www.html5rocks.com/en/'},
        { label:'JS 优质内容',prop:'JS 优质内容',page:'http://www.echojs.com/'},
        { label:'移动端 Web 开发',prop:'移动端 Web 开发',page:'https://mobiledevweekly.com/'},
        { label:'VScode快捷键介绍',prop:'VScode快捷键介绍',page:'https://www.cnblogs.com/bindong/p/6045957.html'},
        { label:'Socket通信',prop:'Socket通信',page:'https://socket.io/'},
        { label:'JSONPlaceholder',prop:'JSONPlaceholder',page:'http://jsonplaceholder.typicode.com/'},
        { label:'拉勾网',prop:'拉勾网',page:'https://www.lagou.com/'},
        { label:'Boss直聘',prop:'Boss直聘',page:'https://www.zhipin.com/?sid=sem_pz_bdpc_dasou_title'},
        { label:'猎聘网',prop:'猎聘网',page:'https://www.liepin.com/'},
        { label:'智联招聘',prop:'智联招聘',page:'http://landing.zhaopin.com/register'},
        { label:'一早一晚',prop:'一早一晚（国内远程工程师招聘）',page:'https://yizaoyiwan.com/'},
        { label:'接项目接私活的网站总结',prop:'接项目接私活的网站总结',page:'https://blog.csdn.net/weixin_43606158/article/details/90728142'},
        { label:'web开发互助网',prop:'web开发互助网',page:'http://hz.uyi2.com/'},
        { label:'前端面试题一到三年',prop:'前端面试题一到三年',page:'https://blog.csdn.net/weixin_43606158/article/details/89811189'},
        { label:'前端面试题三到五年',prop:'前端面试题三到五年',page:'https://blog.csdn.net/weixin_43606158/article/details/89640672'},
        { label:'React 新闻订阅',prop:'React 新闻订阅',page:'http://reactjsnewsletter.com/issues'},
        { label:'节点周刊',prop:'节点周刊',page:'https://nodeweekly.com/'},
        { label:'前端焦点',prop:'前端焦点',page:'https://frontendfoc.us/'},
        { label:'资源数据',prop:'资源数据',page:'https://www.ceicdata.com'},
        { label:'投资界新闻',prop:'投资界新闻',page:'https://news.pedaily.cn/'},
      ],
    },
  ],
}
export default layout;
